Developer Tutorial Move - 1
FaradayRF/Faraday-Software pull request #106
Opened 2017-02-23 09:28 UTC by kb1lqd

h1. Updates

Python_Developers_Tutorial folder contains:
* "foundation" folder
* "miscellaneous" folder

Removed folders:
* 1-Basic_Proxy_Interactions_And_Programming
* 2-Advanced_Proxy_Programs

Renamed Folders
* Simply removed the numbers prefixed to the folder names of the tutorials in the
foundation/miscellaneous folders.

Other:
* Update Readme.md to latest
* Fixed basic spelling typo's in readme.md
* Moved Readme.md from "Tutorials" folder to "Python_Developer_Tutorials" folder

2017-02-23 09:47 UTC, kb1lqc requested changes
One simple blocking change that you should note what isn't updated so when this is merged people know what is old/stale/outdated on the readme.md

2017-02-23 09:47 UTC, kb1lqc commented on Tutorials/Python_Developer_Tutorials/Readme.md
> +This tutorial series is focused on introducing Faraday as a digital radio platform to program using Python. The reader will begin by learning fundamental transmissions of commands to both local and r
## Non-Blocking
* Spelling: http://www.dictionary.com/browse/toolset
* Wording "The tutorial series will conclude by building upon each skill and tool-set learned to develop a basic radio data  transmission program capable of transmitting data, text, etc... of arbitrary size from one Faraday to another through wireless transmissions." for example uses transmission or transmissions a lot which sounds weird.

2017-02-23 09:47 UTC, kb1lqc commented on Tutorials/Python_Developer_Tutorials/Readme.md
> +* Programming with Faraday tool-sets/modules
## Non-Blocking
* Spelling: http://www.dictionary.com/browse/toolset

2017-02-23 09:47 UTC, kb1lqc commented on Tutorials/Python_Developer_Tutorials/Readme.md
> +> These tutorials rely on the currently implemented commands/functionality of Faraday and thus provide a great platform for experimentation. Higher data throughput and functionality can be achieved u
## Non-Blocking
* Spelling: http://www.dictionary.com/browse/toolset

2017-02-23 09:47 UTC, kb1lqc commented on Tutorials/Python_Developer_Tutorials/Readme.md
> +##Introduction To Faraday Proxy Programming
## Blocking
* I would label what is complete and what is not with a little note i.e

**[Commanding - Local](foundation/Commanding-Local/)** (Outdated)

2017-02-24 07:37 UTC, kb1lqd commented on Tutorials/Python_Developer_Tutorials/Readme.md
> +This tutorial series is focused on introducing Faraday as a digital radio platform to program using Python. The reader will begin by learning fundamental transmissions of commands to both local and r
Fixed typo, reworded.

2017-02-24 07:37 UTC, kb1lqd commented on Tutorials/Python_Developer_Tutorials/Readme.md
> +* Programming with Faraday tool-sets/modules
Fixed.

2017-02-24 07:38 UTC, kb1lqd commented on Tutorials/Python_Developer_Tutorials/Readme.md
> +##Introduction To Faraday Proxy Programming
Added notes.

2017-02-24 07:40 UTC, kb1lqd commented
@kb1lqc updates performed per review, ready for re-review.

2017-02-24 08:05 UTC, kb1lqc requested changes
Wording is off and a tad confusing. Fix those and it should be good.

2017-02-24 08:05 UTC, kb1lqc commented on Tutorials/Python_Developer_Tutorials/Readme.md
> +This tutorial series is focused on introducing Faraday as a digital radio platform. The reader will begin by learning fundamental commands used to used to both communicate with a locally connected Fa
"...commands used to used to both communicate..." makes no sense

2017-02-24 08:05 UTC, kb1lqc commented on Tutorials/Python_Developer_Tutorials/Readme.md
> +  * This example tutorial implements the "Simple Text Messaging" application into a generic transmitter/receiver python object. This is a major step towards implemented a RESTful FLASK based applicat
- implemented should be "implementing"
- FLASK should be Flask

2017-02-24 08:08 UTC, kb1lqd commented on Tutorials/Python_Developer_Tutorials/Readme.md
> +This tutorial series is focused on introducing Faraday as a digital radio platform. The reader will begin by learning fundamental commands used to used to both communicate with a locally connected Fa
Fixed.

2017-02-24 08:08 UTC, kb1lqd commented on Tutorials/Python_Developer_Tutorials/Readme.md
> +  * This example tutorial implements the "Simple Text Messaging" application into a generic transmitter/receiver python object. This is a major step towards implemented a RESTful FLASK based applicat
Fixed.

2017-02-24 08:21 UTC, kb1lqc approved these changes
Thanks for updating the wording. Looks good.

2017-02-24 08:23 UTC, merged