Issue120: Telemetry Application Should Handle Exceptions Better
FaradayRF/Faraday-Software pull request #125
Opened 2017-03-05 07:01 UTC by kb1lqc

Implemented #120 fixes which overall makes the program much more robust to configuration file errors such as missing files, missing sections, incorrect user input, etc. It also fails gracefully wherever possible and will prevent the program from progressing for fatal errors such as configuration file import errors. Indicating what is wrong so a false sense of operation is not given.

Several API bugs were also fixed as they were found.

Additionally, comments and docstrings were updated. Formatting was not largely considered so this merge does not include PEP8 updates per our contributions.md.

# Changes
## Global
-Update loggingConfig.ini and telemetry.ini config file reads to check for errors and get stuck in infinite loops if an error occurs. Update once per second with error message.

## telemworker()
- Properly detect bad settings or no data with try/except statements as well as type checking for a dictionary indicating an Error as data is sent back in lists.
- Update docstring
- Changed main data `while(1):` to `while True:`

## / app.route()
- Updated docstring
- Try/except statement for request argument gets
- Added local variable initialization section

## /stations app.route()
- Removed unnecessary `.upper()` on `telemetry.py` line 357. Already present on line 333
- Improved callsign specific query
- added nodeid query to correctly implement nodeid
- Use generateStartStopTimes() instead of manually performing function when defined function already exists
- Updated request exception with IOError, removed unused exceptions
- Properly return an HTTP204 when no stations are heard that match query parameters

## generateStartStopTimes()
- Updated docstring
- Updated starttime sensing to detect when a start time was provided without endtime

## initDB()
- Added ConfigParser exception
- Added Sqlite3 exception
- Changed return into True/False on success
- Updated docstring

## createTelemetryList()
- Updated docstring
- Return temp = [] if KeyError occurs

## sqlInsert()
- Added len(telem) check
- Updated docstring
- Return True or False on insertion success
- Cleaned up SQLite3 exception handling
- Add try statements to compartmentalize exceptions

## iso8601ToEpoch()
- Updated docstring

## queryDB():
- added check for timeTuple == None
- Updated queryDb() docstring
- Removed unnecessary upper() from parameter["CALLSIGN"] variable declaration in queryDb as it is specified to be uppercase when input
- Added debug logger `logger.debug(sql)` to queryDb()
- Moved sqlData variable declaration to top of queryDb()
- Added telemetryConfig.Error exception to queryDb() filename read. Logs error and returns empty sqlData list.
- Removed unnecessary Exceptions from queryDb database connection code, uses ProgrammingError and StandardError only. Both exceptions return empty sqlData list and close database connections.
- queryDb() row to sqlData insertion try/except statement only uses StandardError and closes connection followed by returning sqlData.
- Tested raising StandardError and sqlite3.Error exceptions to confirm those errors are caught and responded to correctly.

## main()
- Added exception handling for ConfigParser
- Updated docstring

## queryStationsDb()
- Update docstring
- Fixed callsign parameter SQL comment to remove erroneous sqlend reference
- Updated comment when no callsign is specified
- Fixed "database" comment spelling
- Added try statement with ConfigParser.Error exception for database filename
- Cleaned up sqlite3 connection and execution exceptions, returns sqlData after an exception and closes the database connection when it is open during an exception.
- Updated logger text when no stations are returned from /stations query
- Added else statement for check if callsing and nodeid are `None`. If length is zero indicating no data in queue a HTTP204 is returned.

## /raw app.rout()
- Improved and simplified request argument exceptions
- Simplified argument checking exceptions to use ValueError only when raising an exception
- Added comments about telemetryDict and fixed spelling error "two"
- Spelling error "dumps"

## querystationsdb()
- Added more informative "ProgrammingError" log string to `queryStationsDb()`

2017-03-07 16:24 UTC, kb1lqd requested changes
Can you break this up into smaller PR's?

2017-03-07 16:24 UTC, kb1lqd commented on Applications/Telemetry/telemetry.py
> +try:
Confirmed check works as intended.

2017-03-07 16:24 UTC, kb1lqd commented on Applications/Telemetry/telemetry.py
> +telemetryFile = telemetryConfig.read('telemetry.ini')
Check works as intended.

2017-03-07 16:24 UTC, kb1lqd commented on Applications/Telemetry/telemetry.py
> +    telemetry to a specific unit with this application. This function runs
Ok.

2017-03-07 16:24 UTC, kb1lqd commented on Applications/Telemetry/telemetry.py
> +        count = config.getint("TELEMETRY", "UNITS")
OK. Count is initialized to 0 prior for good measure.

2017-03-22 04:26 UTC, kb1lqd commented
@kb1lqc This is now 17 days old. Lets get a plan to get this through efficiently by optimized review scope/risk, knowledge, and possibly breaking it up as needed.

2017-03-23 07:53 UTC, kb1lqc commented
@kb1lqd Yeah I think we should simply tag-up and walk through this. Long-term we should honestly rely on automated tests (submitted with PR) and basically double-check for style and a quick run-through of the code. Until we get that setup we'll probably be a tad slow on this. Unfortunately this came before I needed to step away from development for a week or so which resulted in the extended timeline.

2017-03-29 05:36 UTC, kb1lqd commented on Applications/Telemetry/telemetry.py
> +    count = 0
Count of units in config file.

2017-03-29 05:38 UTC, kb1lqd commented on Applications/Telemetry/telemetry.py
> +                time.sleep(1)
Looks good, infinite loop if config error.

2017-03-29 05:39 UTC, kb1lqd commented on Applications/Telemetry/telemetry.py
> +
Looks good, just added try and exeption.

2017-03-29 05:39 UTC, kb1lqd commented on Applications/Telemetry/telemetry.py
> +    while True:
Looks good, PEP8 mostly.

2017-03-29 05:43 UTC, kb1lqd commented on Applications/Telemetry/telemetry.py
> +                logger.debug("Proxy data: " + repr(data))
If valid data: Get list of HTTP 200 JSON dictionaries of data
If error from proxy: Get single HTTP 404 JSON dictionary item
Should never be None except if never set.

2017-03-29 05:47 UTC, kb1lqd commented on Applications/Telemetry/telemetry.py
> +        logger.error("IOError: " + str(e))
IOerror check due to requests.

2017-03-29 05:48 UTC, kb1lqd commented on Applications/Telemetry/telemetry.py
> -    parameters = {}
Assumes local function variables are lost after runtime and reset to default nothing.

2017-03-29 05:49 UTC, kb1lqd commented on Applications/Telemetry/telemetry.py
> -    data = []
Assumes local variables are lost after function run-time and don't need re-initialization to clear old values.

2017-03-29 05:51 UTC, kb1lqd commented on Applications/Telemetry/telemetry.py
> +    stationData = []
Needed to initialize?

2017-03-29 05:51 UTC, kb1lqd commented on Applications/Telemetry/telemetry.py
> +        logger.error("IOError: " + str(e))
IOerror check due to requests.

2017-03-29 05:54 UTC, kb1lqd commented on Applications/Telemetry/telemetry.py
> +    stationData = []
Is needed due to potential for no stations to be present prior to len() check later when no variable is present.

2017-03-29 05:56 UTC, kb1lqd commented on Applications/Telemetry/telemetry.py
> +                raise ValueError(message)
Removed redundant error 400 from below.

2017-03-29 05:59 UTC, kb1lqd commented on Applications/Telemetry/telemetry.py
> -                    stationData = []
removed a stationdata list init?

2017-03-29 06:00 UTC, kb1lqd commented on Applications/Telemetry/telemetry.py
> -                    stationData = []
No reason to erase anything from stationdata. OK.

2017-03-29 06:01 UTC, kb1lqd commented on Applications/Telemetry/telemetry.py
> +
OK will have to watch this.

2017-03-29 06:03 UTC, kb1lqd commented on Applications/Telemetry/telemetry.py
> +    # Completed our query for "/raw", return json.dumps() and HTTP 200
OK, looks good.

2017-03-29 06:04 UTC, kb1lqd commented on Applications/Telemetry/telemetry.py
> +        return json.dumps({"error": str(e)}), 400
IOerror check due to requests library.

2017-03-29 06:05 UTC, kb1lqd commented on Applications/Telemetry/telemetry.py
> +    parameters["CALLSIGN"] = callsign
Removal OK because config get above forces upper already.

2017-03-29 06:07 UTC, kb1lqd requested changes
Typo.

2017-03-29 06:07 UTC, kb1lqd commented on Applications/Telemetry/telemetry.py
> +        logger.info("No Station have been heard in last %d seconds", timespan)
Typo: station should be "stations"

2017-03-29 06:08 UTC, kb1lqd commented on Applications/Telemetry/telemetry.py
> +    """
OK.

2017-03-29 06:08 UTC, kb1lqd commented on Applications/Telemetry/telemetry.py
> +        return False
IOerror check for config parser.

2017-03-29 06:09 UTC, kb1lqd commented on Applications/Telemetry/telemetry.py
> +    return True
Errors gracefully if database issue. OK.

2017-03-29 06:10 UTC, kb1lqd commented on Applications/Telemetry/telemetry.py
> +        temp = []
Only added try and specific key error. izz cool.

2017-03-29 06:14 UTC, kb1lqd commented on Applications/Telemetry/telemetry.py
> +    # Change dictionary into list with proper order
Specific error for config program.

2017-03-29 06:15 UTC, kb1lqd commented on Applications/Telemetry/telemetry.py
> +            return False
OK. Avoids no telem causing failure. A safe way to create SQL commands.

2017-03-29 06:16 UTC, kb1lqd commented on Applications/Telemetry/telemetry.py
> +                conn.execute(sql,telem)
OK. Executing prior developed SQL command.

2017-03-29 06:18 UTC, kb1lqd requested changes
Need to add SQL safe to corrupted data in event of failure.

2017-03-29 06:18 UTC, kb1lqd commented on Applications/Telemetry/telemetry.py
> +            return False
You should do a roll-back to throw out SQL edits if error occurs to avoid corrupting database.

2017-03-29 06:23 UTC, kb1lqd commented on Applications/Telemetry/telemetry.py
> +        rows = cur.fetchall()
First addition to sqldata. This is running in a loop.

2017-03-29 06:29 UTC, kb1lqd requested changes
sqlData variable returned when always empty.

2017-03-29 06:29 UTC, kb1lqd commented on Applications/Telemetry/telemetry.py
> +    sqlData = []
No reason to declare at start of function. Remove.

2017-03-29 06:29 UTC, kb1lqd commented on Applications/Telemetry/telemetry.py
> +        return sqlData
sqlData will always be empty, why return? Remove.

2017-03-29 06:29 UTC, kb1lqd commented on Applications/Telemetry/telemetry.py
> +        return sqlData
sqlData will always be empty, why return? Remove.

2017-03-29 06:29 UTC, kb1lqd commented on Applications/Telemetry/telemetry.py
> +        return sqlData
sqlData will always be empty, why return? Remove.

2017-03-29 06:29 UTC, kb1lqd commented on Applications/Telemetry/telemetry.py
> +        return sqlData
sqlData will always be empty, why return? Remove.

2017-03-29 06:31 UTC, kb1lqd commented on Applications/Telemetry/telemetry.py
> +        rows = cur.fetchall()
Fetch all rows that match.

2017-03-29 06:36 UTC, kb1lqd requested changes
more sqlData returns as empty.

2017-03-29 06:36 UTC, kb1lqd commented on Applications/Telemetry/telemetry.py
> +    sqlData = []
Don't initialize at start of function if not needed.

2017-03-29 06:36 UTC, kb1lqd commented on Applications/Telemetry/telemetry.py
> +        return sqlData
sqlData will always be empty, why return? Remove.

2017-03-29 06:36 UTC, kb1lqd commented on Applications/Telemetry/telemetry.py
> +        return sqlData
sqlData will always be empty, why return? Remove.

2017-03-29 06:36 UTC, kb1lqd commented on Applications/Telemetry/telemetry.py
> +        return sqlData
sqlData will always be empty, why return? Remove.

2017-03-29 06:38 UTC, kb1lqd commented on Applications/Telemetry/telemetry.py
> +        return sqlData
Another SQLdata empty?

2017-03-29 06:40 UTC, kb1lqd commented on Applications/Telemetry/telemetry.py
> +        return None
Thus function looks OK.

2017-03-29 06:40 UTC, kb1lqd commented on Applications/Telemetry/telemetry.py
> +            time.sleep(1)
Added try and except specific to config parser.

2017-03-29 06:41 UTC, kb1lqd commented
@kb1lqc Ready for your responses/fixes.

2017-03-29 06:47 UTC, kb1lqc commented on Applications/Telemetry/telemetry.py
> +        logger.info("No Station have been heard in last %d seconds", timespan)
Fixed

2017-03-29 06:51 UTC, kb1lqc commented on Applications/Telemetry/telemetry.py
> +            return False
Added rollback() after execution of SQL

2017-03-29 06:53 UTC, kb1lqc commented on Applications/Telemetry/telemetry.py
> +    sqlData = []
Removed

2017-03-29 07:08 UTC, kb1lqc commented on Applications/Telemetry/telemetry.py
> +    sqlData = []
Actually added back in, I realized that sqlData is a convenient way to return an empty list when an error occurs. This simplifies the downstream logic.

2017-03-29 07:08 UTC, kb1lqc commented on Applications/Telemetry/telemetry.py
> +        return sqlData
See above comment for line 601

2017-03-29 07:08 UTC, kb1lqc commented on Applications/Telemetry/telemetry.py
> +        return sqlData
See above comment for line 601

2017-03-29 07:08 UTC, kb1lqc commented on Applications/Telemetry/telemetry.py
> +        return sqlData
See above comment for line 601

2017-03-29 07:08 UTC, kb1lqc commented on Applications/Telemetry/telemetry.py
> +        return sqlData
See above comment for line 601

2017-03-29 07:08 UTC, kb1lqc commented on Applications/Telemetry/telemetry.py
> +    sqlData = []
See above comment for line 601

2017-03-29 07:08 UTC, kb1lqc commented on Applications/Telemetry/telemetry.py
> +        return sqlData
See above comment for line 601

2017-03-29 07:09 UTC, kb1lqc commented on Applications/Telemetry/telemetry.py
> +        return sqlData
See above comment for line 601

2017-03-29 07:09 UTC, kb1lqc commented on Applications/Telemetry/telemetry.py
> +        return sqlData
See above comment for line 601

2017-03-29 07:09 UTC, kb1lqc commented on Applications/Telemetry/telemetry.py
> +        return sqlData
See above comment for line 601

2017-03-29 07:18 UTC, kb1lqd approved these changes

2017-03-29 07:20 UTC, kb1lqd commented
Approving. This PR runs telemetry as intended and I can query for stations as expected. Both local and RF unit received over several minutes. Some functionality left untested such as proper error handling and SQL rollback better handled by automated testing.

2017-03-29 07:20 UTC, merged