Continuing code style cleanup
FaradayRF/Faraday-Software pull request #143
Opened 2017-04-04 05:38 UTC by reillyeon

Fixed errors E101, E111, E116, E123, E124, E126, E127 and E128.

2017-04-04 07:27 UTC, kb1lqc requested changes
Please pull in the latest master to make sure this is still valid with the hermes and other code that has been modified. Looks good otherwise but I will need to check it with hardware prior to approving to ensure it doesn't break the software. I'm definitely cautious of the APRS changes and if they cause anything to break.

2017-04-04 07:27 UTC, kb1lqc commented on presubmit.sh
> +flake8 --ignore=E116,E123,E124,E126,E127,E128,E201,E202,E203,E211,E221,E222,E225,E226,E227,E228,E231,E251,E261,E262,E265,E266,E402,E501
Didn't you get rid of presubmit.sh with pytest?

2017-04-04 07:27 UTC, kb1lqc commented on Applications/APRS/aprs.py
> +                positionString = '{}>{},{},{}:{}.../{}/A={}{}\r'.format(
Interesting use of a format(), very close to how `aprslib` does it. This code is going to be replaced by `aprslib` functions in the future FYI. I do want @kb1lqd to see this. Nifty formatting. WAYY cleaner than how I did it prior.

2017-04-04 15:23 UTC, binaryfox0 commented on presubmit.sh
> +flake8 --ignore=E116,E123,E124,E126,E127,E128,E201,E202,E203,E211,E221,E222,E225,E226,E227,E228,E231,E251,E261,E262,E265,E266,E402,E501
Separate pull request. I wasn't sure which order you'd get to them in.

2017-04-04 15:24 UTC, reillyeon commented on presubmit.sh
> +flake8 --ignore=E116,E123,E124,E126,E127,E128,E201,E202,E203,E211,E221,E222,E225,E226,E227,E228,E231,E251,E261,E262,E265,E266,E402,E501
I wasn't sure which order you'd get to these pull requests in so I based this one on master.

2017-04-05 04:28 UTC, kb1lqc commented
looking good @reillyeon, Please fix the conflicting `presubmit.sh` and I'll merge!

2017-04-05 04:40 UTC, kb1lqc commented
Awesome just saw these commits. @reillyeon are you planning on pushing more to this PR?

2017-04-05 04:41 UTC, reillyeon commented
I have a few more errors I might get to before the night is done, but please merge this now.

2017-04-05 04:43 UTC, kb1lqc commented
OK I think I'll get some stuff done on other Faraday items I was planning on doing tonight before moving over to this as I need to check it with hardware given the breadth of these changes.

2017-04-05 07:36 UTC, kb1lqc commented on Firmware_Bootstrap_Loader/faradaybsl/createtiscripter.py
> +            script_index_crc = "CRC_CHECK 0x{} {} {}".format(
Looks benign but alerting @kb1lqd to some changes to the bootstrap loader. I'm tempted to pull this in without running it through firmware loading. You OK with remembering that this was touched if we encounter errors with bootstrap loading in the future?

2017-04-05 07:48 UTC, kb1lqc approved these changes

2017-04-05 07:55 UTC, kb1lqc commented
Checked the following applications with hardware:
- Proxy
- Telemetry
- APRS
- Hermes
- Simpleconfig
- Readconfig
- Deviceconfig

I did not check the bootstrap loader but this may be acceptable. Thoughts @kb1lqd ?

2017-04-06 05:23 UTC, kb1lqd commented on Firmware_Bootstrap_Loader/faradaybsl/createtiscripter.py
> +            script_index_crc = "CRC_CHECK 0x{} {} {}".format(
I just testing @reillyeon branch and it fails. It hang's up. Master works fine.

![image](https://cloud.githubusercontent.com/assets/339144/24739001/6880b27c-1a4e-11e7-9178-238003794fce.png)

2017-04-06 05:43 UTC, kb1lqc commented on Proxy/faraday_uart_stack/layer_2_protocol.py
> +                if self.ser.inWaiting() > 0:
Seems benign but also suspicious

2017-04-06 05:47 UTC, kb1lqc requested changes
Need to figure out why BSL isn't working right.

2017-04-06 05:49 UTC, reillyeon commented
As far as I can tell my branch is generating the same `FaradayFirmwareUpgradeScript.txt`. It's the actual firmware update tool that is crashing in your screenshot. Very odd indeed.

2017-04-06 06:07 UTC, kb1lqc commented
@reillyeon and @kb1lqd This appears to work fine for me...
![bootstrap](https://cloud.githubusercontent.com/assets/331540/24740150/94e41e52-1a54-11e7-9f4f-bba3a727284a.gif)

2017-04-06 06:44 UTC, kb1lqd commented on Firmware_Bootstrap_Loader/faradaybsl/createtiscripter.py
> +            script_index_crc = "CRC_CHECK 0x{} {} {}".format(
OK So it was a folder permission or something on my computer. I copied all of the BSL folder contents into my master and ran it with success as well.

I made a fake firmware version with "5555" for firmware to verify firmware loading.

![image](https://cloud.githubusercontent.com/assets/339144/24741185/c8a01c64-1a59-11e7-85a2-7b55760d0636.png)

2017-04-06 06:58 UTC, kb1lqc approved these changes

2017-04-06 06:59 UTC, kb1lqc commented
@kb1lqd confirmed this works with the Bootstrap Loader. He has some file permission error on his computer that was cleared by changing directories. Merging.

2017-04-06 06:59 UTC, merged