Packaging DeviceConfiguration and SimpleConfig Applications
FaradayRF/Faraday-Software pull request #219
Opened 2017-06-30 15:10 UTC by kb1lqc

This PR updates the Device Configuration and SimpleConfig applications to be imported into the python package for `faraday`. It may not be implemented the cleanest (see --fxxxxx options) but it is pretty straightforward and we can improve in later updates. The distribution files have been uploaded to TestPyPi to allow pip installation from the test repository. Alternatively you can install this git branch in editable mode with `pip install -e .` from the main folder.

@kb1lqd @el-iso  @jbemenheiser  @reillyeon

# Change Log
- Moved deviceconfiguration into `--faraday-deviceconfiguration`
- Moved simpleconfig into `--faraday-simpleconfig`
- Moved configuration files `deviceconfiguration.sample.ini` and `faraday_config.sample.ini` into etc/faraday
- Updated setup.cfg to reflect new version + new etc/files with commands for these two programs
- Changed `deviceconfiguration.ini` [DEVICES] options for use with one radio at a time. This simplified the code and really we only want to program one radio at a time right now. Future updates can expand this.
- Added [PROXY] section to `deviceconfiguration.sample.ini`
- Added appropriate loggers for Device Configuration and SimpleConfig programs to `loggingConfig.ini`
- Updated **ALL programs** loggers in `loggingConfig.ini` to INFO level
- Added command line options for `faraday-deviceconfiguration` and `faraday-simpleconfig`
- Added functionality to simpleconfig to read only and not program

# Command Line Options
## Device Configuration
```
$ faraday-deviceconfiguration --help
usage: faraday-deviceconfiguration [-h] [--init-config]
                                   [--init-faraday-config]
                                   [--callsign CALLSIGN] [--nodeid NODEID]
                                   [--faradayconfig] [--fcallsign FCALLSIGN]
                                   [--fnodeid FNODEID] [--fconfigboot]
                                   [--fgpiop3 FGPIOP3] [--fgpiop4 FGPIOP4]
                                   [--fgpiop5 FGPIOP5]
                                   [--fbootfrequency FBOOTFREQUENCY]
                                   [--fbootrfpower FBOOTRFPOWER]
                                   [--flatitude FLATITUDE]
                                   [--flongitude FLONGITUDE]
                                   [--flatitudedir FLATITUDEDIR]
                                   [--flongitudedir FLONGITUDEDIR]
                                   [--faltitude FALTITUDE] [--fgpsboot]
                                   [--fgps] [--fuarttelemetry]
                                   [--frftelemetry]
                                   [--fuartinterval FUARTINTERVAL]
                                   [--frfinterval FRFINTERVAL]

Device Configuration application provides a Flask server to program Faraday
radios via an API

optional arguments:
  -h, --help            show this help message and exit
  --init-config         Initialize Device Configuration configuration file
  --init-faraday-config
                        Initialize Faraday configuration file
  --callsign CALLSIGN   Set Proxy Faraday callsign to connect to and program
  --nodeid NODEID       Set Proxy Faraday nodeid to connect to and program
  --faradayconfig       Display Faraday configuration file contents
  --fcallsign FCALLSIGN
                        Set Faraday radio callsign
  --fnodeid FNODEID     Set Faraday radio nodeid
  --fconfigboot         Set Faraday radio config boot bit OFF
  --fgpiop3 FGPIOP3     Set Faraday radio fgpio_p3
  --fgpiop4 FGPIOP4     Set Faraday radio fgpio_p4
  --fgpiop5 FGPIOP5     Set Faraday radio fgpio_p5
  --fbootfrequency FBOOTFREQUENCY
                        Set Faraday radio boot frequency
  --fbootrfpower FBOOTRFPOWER
                        Set Faraday radio boot RF power
  --flatitude FLATITUDE
                        Set Faraday radio default latitude. Format "ddmm.mmmm"
  --flongitude FLONGITUDE
                        Set Faraday radio default longitude. Format
                        "dddmm.mmmm"
  --flatitudedir FLATITUDEDIR
                        Set Faraday radio default latitude direction (N/S)
  --flongitudedir FLONGITUDEDIR
                        Set Faraday radio default longitude direction (E/W)
  --faltitude FALTITUDE
                        Set Faraday radio default altitude in meters. Maximum
                        of 17999.99 Meters
  --fgpsboot            Set Faraday radio GPS boot power OFF
  --fgps                Set Faraday radio GPS use ON
  --fuarttelemetry      Set Faraday radio UART Telemetry OFF
  --frftelemetry        Set Faraday radio RF Telemetry ON
  --fuartinterval FUARTINTERVAL
                        Set Faraday radio UART telemetry interval in seconds
  --frfinterval FRFINTERVAL
                        Set Faraday radio RF telemetry interval in seconds
```

## SimpleConfig
```
$ faraday-simpleconfig --help
usage: faraday-simpleconfig [-h] [--read]

SimpleConfig sends a request to faraday-deviceconfiguration to initiate a POST
or GET command resulting in programming a Faraday radio and/or reading its
FLASH memory configuration

optional arguments:
  -h, --help  show this help message and exit
  --read      Read FLASH configuration only, do not program
```

# Installing from TestPyPi
As of this PR creation the latest package on TestPyPi is [farday-0.0.1014.dev1068](https://testpypi.python.org/pypi/faraday/0.0.1014.dev1068)

Install with `pip install --no-cache-dir --extra-index-url https://testpypi.python.org/pypi faraday`

Ensure you are installing this correct version per this PR

2017-07-01 18:14 UTC, reillyeon commented
Skimming through the help info it seems unnecessary to prefix all the options with "f".

2017-07-02 15:13 UTC, kb1lqc commented
@reillyeon I actually prefix the options which change actual faraday programmed memory with an `--f`. Therefore as it currently stands `--callsign` changes the device configuration program callsign setting while `--fcallsign` changes the intended callsign to be programmed to faraday. Any other suggestions?

2017-07-02 19:10 UTC, kb1lqd commented
@kb1lqc Why not just use the terms `--proxycallsign` to change local connection callsign and just `--callsign` for the device configuration update callsign? I agree with @reillyeon that prepending `f` before each command is unnecessary.

2017-07-02 19:24 UTC, kb1lqc commented
OK I'll update shortly @kb1lqd  @reillyeon

2017-07-02 19:37 UTC, kb1lqd commented
@kb1lqc How does `faraday-deviceconfiguration --fconfigboot` work? I can't seem to get it to do anything. Also this should not simply be the only way to edit the configbootbitmask. We should have a way to set the bitmask manually to a value (byte) and/or also support the "RF RED LED" bit 1 as well.

2017-07-02 19:52 UTC, kb1lqd requested changes

2017-07-02 19:52 UTC, kb1lqd commented on faraday/deviceconfiguration.py
> +parser.add_argument('--callsign', help='Set Proxy Faraday callsign to connect to and program')
This should be `--proxycallsign` or similar and allow the removal of `f` prepending the other arguments.

2017-07-02 19:52 UTC, kb1lqd commented on faraday/deviceconfiguration.py
> +parser.add_argument('--fconfigboot', action='store_false', help='Set Faraday radio config boot bit OFF')
1) This doesn't seem to work... Also how do you toggle this back ON? (This is BIT 0)
2) Need to add for BIT 1 the toggling of the RED LED action on RF TX

If both bits are high then config boot bitmask = 3 (00000011)

2017-07-02 19:52 UTC, kb1lqd commented on faraday/deviceconfiguration.py
> +parser.add_argument('--fgpsboot', action='store_false', help='Set Faraday radio GPS boot power OFF')
How do you toggle back on? I suggest either allowing argument options `0` and '1' or creating an `ON` and `OFF` function arguments.

2017-07-02 19:52 UTC, kb1lqd commented on faraday/deviceconfiguration.py
> +parser.add_argument('--fgps', action='store_true', help='Set Faraday radio GPS use ON')
How do you toggle back on? I suggest either allowing argument options `0` and '1' or creating an `ON` and `OFF` function arguments.

2017-07-02 19:52 UTC, kb1lqd commented on faraday/deviceconfiguration.py
> +parser.add_argument('--fuarttelemetry', action='store_false', help='Set Faraday radio UART Telemetry OFF')
How do you toggle back on? I suggest either allowing argument options 0 and '1' or creating an ON and OFF function arguments.

2017-07-02 19:52 UTC, kb1lqd commented on faraday/deviceconfiguration.py
> +parser.add_argument('--frftelemetry', action='store_true', help='Set Faraday radio RF Telemetry ON')
How do you toggle back off? I suggest either allowing argument options 0 and '1' or creating an ON and OFF function arguments.

2017-07-02 19:53 UTC, kb1lqc commented
@kb1lqd maybe I misunderstood the value. You can just turn it ON/OFF. Not placing `--configboot` in the command will default to setting the INI file to a value of 1 and by specifying `--configboot` you change it to a zero. This is explained in the `--help` option.

2017-07-02 19:55 UTC, kb1lqc commented on faraday/deviceconfiguration.py
> +parser.add_argument('--callsign', help='Set Proxy Faraday callsign to connect to and program')
Changed in https://github.com/FaradayRF/Faraday-Software/pull/219/commits/1556fe743c340aa67beec7e3e4849fb19021df27

2017-07-02 19:56 UTC, kb1lqc commented on faraday/deviceconfiguration.py
> +parser.add_argument('--fconfigboot', action='store_false', help='Set Faraday radio config boot bit OFF')
@kb1lqd 

1. It defaults to 1 and if you specify `--configboot` the INI file is changed to a zero.
2. Looks like I implemented it wrong haha....

2017-07-02 19:57 UTC, kb1lqc commented on faraday/deviceconfiguration.py
> +parser.add_argument('--fgpsboot', action='store_false', help='Set Faraday radio GPS boot power OFF')
Defaults to ON. I should update the help description to state this.

2017-07-02 19:57 UTC, kb1lqc commented on faraday/deviceconfiguration.py
> +parser.add_argument('--fgps', action='store_true', help='Set Faraday radio GPS use ON')
Defaults to OFF, I should add more to the help statement.

2017-07-02 19:58 UTC, kb1lqc commented on faraday/deviceconfiguration.py
> +parser.add_argument('--fuarttelemetry', action='store_false', help='Set Faraday radio UART Telemetry OFF')
Defaults to ON, will add statement to --help description

2017-07-02 19:58 UTC, kb1lqc commented on faraday/deviceconfiguration.py
> +parser.add_argument('--frftelemetry', action='store_true', help='Set Faraday radio RF Telemetry ON')
Defaults to OFF, will add help information about this.

2017-07-02 19:59 UTC, kb1lqc commented
@kb1lqd just responded to your questions. Overall I basically made any ON/OFF option in _faraday.ini_ default to what we have in the _faraday.sample.ini_ configuration.

I do think I completely missimplemented the `--configboot` option. Should we coverse more about how to implement each bit now or in a later PR and remove the option for the time being?

2017-07-02 20:03 UTC, kb1lqd commented
@kb1lqc Yeah this is not a fun way to do it for several reason:
* Editing multiple units with multiple settings (or making a mistake and wanting a different option) means re initializing the whole file.
* Defaulting to a standard setting is fine but any bit toggling NEED's both ON and OFF due to the above

Also, the bitmask bytes are literally bitmask bytes so all bits in use need to be editable. This is not acceptable for a later PR since things like the RED LED toggle are very useful and should be supported off the bat as they currently are.

2017-07-02 20:24 UTC, kb1lqc commented
@kb1lqd what are the bitmask values? what does each bit represent?

2017-07-02 20:32 UTC, kb1lqd commented
[Flash_Info_D_Memory_Allocations.xlsx](https://github.com/FaradayRF/Faraday-Software/files/1118082/Flash_Info_D_Memory_Allocations.xlsx)


We should bring a lot of this non-public facing documentation to public as it should. I think this fell through the cracks until we started needing to reference it again...

2017-07-02 21:15 UTC, kb1lqd requested changes

2017-07-02 21:15 UTC, kb1lqd commented on faraday/deviceconfiguration.py
> +parser.add_argument('--latitudedir', help='Set Faraday radio default latitude direction (N/S)')
This allows other characters besides N/S. Filter?

2017-07-02 21:15 UTC, kb1lqd commented on faraday/deviceconfiguration.py
> +parser.add_argument('--longitudedir', help='Set Faraday radio default longitude direction (E/W)')
This allows other characters besides E/W. Filter?

2017-07-02 21:28 UTC, kb1lqc commented
One thing I noticed @kb1lqd 

![image](https://user-images.githubusercontent.com/331540/27773615-7b2ec3ea-5f32-11e7-82e8-94871fe0a365.png)

We treat the GPS bitmask and telemetry boot bitmask different. I am forced in python to create the integer value from bits for the configboot value but you accept discrete values in the configuration file for items like GPS boot and stuff. Should we be keeping these the same?

2017-07-02 21:33 UTC, kb1lqd commented
We should standardize this but not in this pr. More of a nice too have than
lacking functionality

On Jul 2, 2017 2:28 PM, "Bryce Salmi" <notifications@github.com> wrote:

> One thing I noticed @kb1lqd <https://github.com/kb1lqd>
>
> [image: image]
> <https://user-images.githubusercontent.com/331540/27773615-7b2ec3ea-5f32-11e7-82e8-94871fe0a365.png>
>
> We treat the GPS bitmask and telemetry boot bitmask different. I am forced
> in python to create the integer value from bits for the configboot value
> but you accept discrete values in the configuration file for items like GPS
> boot and stuff. Should we be keeping these the same?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/FaradayRF/Faraday-Software/pull/219#issuecomment-312518065>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAUsyNx_xC-dAbemimcDFYo1NYuGfLCMks5sKAtngaJpZM4OKtOb>
> .
>

2017-07-02 22:10 UTC, kb1lqc commented
@kb1lqd I implemented the GPIO functionality as well as boot bit mask functionality. It's a tad brute forced in some regards so I'll make an issue to specify that we should clean this up and add functions to pragmatically handle the GPIO bitmask creation. Would be a good beginner task to keep open that doesn't affect functionality.

2017-07-03 00:10 UTC, kb1lqd approved these changes
Besides a few potential updates to clarify/improve in the future the code works as expected.

2017-07-03 06:44 UTC, merged