Incorporate Telemetry Application Documentation Updates
FaradayRF/Faraday-Software pull request #84
Opened 2017-02-18 21:20 UTC by kb1lqc

Simple update of the readme.md in the Applications/Telemetry folder and configuration file:

- Updated readme.md
- Telemetry configuration file updated to use uppercase text
- telemetry application updated to correctly use uppercase configuration file

Code formatting was not improved in this update.

2017-02-18 23:58 UTC, kb1lqd requested changes
All looks good except for the response on the telemetry.ini support for multiple units question.

2017-02-18 23:58 UTC, kb1lqd commented on Applications/Telemetry/readme.md
> + * `UNITS` Quantity of Faraday radios connected to computer
Per comment: https://github.com/FaradayRF/Faraday-Software/pull/85/files#r101904990

@kb1lqc the name/description here implies that you can connect multiple units in a single telemetry program. I don't recall this currently supported but is a future enhancement? If this is not currently supported (i.e. someone enter in "UNIT1CALL") then please state this limitation.

2017-02-18 23:58 UTC, kb1lqd commented on Applications/Telemetry/readme.md
> + * `TIMESPAN`: Timespan ending with current time of data to be obtained from SQLite database
@kb1lqc Do you want to give an example of a "Non default 5 minute timespan"? All your examples that limit to time use the default 5 minute. I'm not going to block this for review but your call.

2017-02-19 00:02 UTC, kb1lqc commented on Applications/Telemetry/readme.md
> + * `UNITS` Quantity of Faraday radios connected to computer
This is no different than the current implementation of APRS or Proxy. I've created [Issue #86](https://github.com/FaradayRF/Faraday-Software/issues/86) to document and address this in the future.

2017-02-19 00:06 UTC, kb1lqc commented on Applications/Telemetry/readme.md
> + * `TIMESPAN`: Timespan ending with current time of data to be obtained from SQLite database
Eventually, I think there is a better way to style this entire example of telemetry and other applications. Therefore I'll keep it basic for now and see how people learn from the current documentation and just extrapolating/experimenting. It's relatively straightforward for a developer to figure this out.

Once we get our bearings we can reassess how we do example code and update accordingly. I've created [Issue #87](https://github.com/FaradayRF/Faraday-Software/issues/87) to document and address this need.

2017-02-19 00:16 UTC, kb1lqd commented on Applications/Telemetry/readme.md
> + * `TIMESPAN`: Timespan ending with current time of data to be obtained from SQLite database
From reading this I have no idea what timespan is, can I just say "...&timespan=15"? Is that 15 seconds or minutes or days?

2017-02-19 00:20 UTC, kb1lqd approved these changes

2017-02-19 00:39 UTC, merged